In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

a = np.array([1,2,3,4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [6]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
type(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [8]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
2


In [10]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d)
print(d.ndim)
type(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


numpy.ndarray

In [12]:
e = np.array([1,2,3], dtype = float)
print(e)
e.shape

[1. 2. 3.]


(3,)

In [13]:
d.shape

(1, 3, 3)

In [14]:
c.shape

(3, 3)

In [17]:
f = np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
f.shape

(1, 1, 1, 3, 3)

In [18]:
f.dtype

dtype('int64')

## Accessing/Changing specific elements, rows & columns etc.

In [78]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
print(a.ndim)

2


In [7]:
# Now get a specific element [r,c]
print(a[0,3])
print(a[1,0])

4
8


In [76]:
# To get full row
print(a[1:])
print(a[0:])

[[5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [79]:
# To get full column
print(a[:,0])
print(a[:,-1])

#for 2 columns
# print(a[:, 1:3])   # columns 1 and 2

[1 8]
[ 7 14]


In [11]:
# Now change some numbers
a[0,0] = 10
a

array([[10,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
a[1,0] = 18
a

array([[10,  2,  3,  4,  5,  6,  7],
       [18,  9, 10, 11, 12, 13, 14]])

## Zeros/Ones method in NumPy

In [83]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((3,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full((3,3),50,dtype="int")

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [19]:
np.random.rand(4,4)

array([[0.7755261 , 0.03424609, 0.62933747, 0.86346743],
       [0.12450903, 0.52298565, 0.10758112, 0.68624111],
       [0.94022913, 0.04715388, 0.88941854, 0.14198814],
       [0.87341248, 0.39408115, 0.39295917, 0.9833243 ]])

In [20]:
np.random.randint(1,10, size = (3,3))

array([[8, 3, 9],
       [6, 4, 9],
       [7, 4, 6]], dtype=int32)

In [23]:
np.identity(3, dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Practice Questions

Question #1

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [34]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

print(a[0:3,-5:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [12 12 12 12 12]]


## Question #2

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

 [1 1 1]

 [0 1 0]]

Input 2:

5

Output 1:

[[0 0 1 0 0]

 [0 0 1 0 0]

 [1 1 1 1 1]

 [0 0 1 0 0]

 [0 0 1 0 0]]

In [52]:
import numpy as np

n = 5
a = np.zeros((n,n),dtype="int")
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [53]:
a[2:3] = 1
a[:,2] = 1
a

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

## Arithmetic Operations with NumPy - Maths + Stats

In [55]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [56]:
a+2

array([3, 4, 5, 6, 7])

In [57]:
a**3

array([  1,   8,  27,  64, 125])

In [58]:
a.min()

np.int64(1)

In [59]:
np.min(a)

np.int64(1)

In [61]:
a.max()

np.int64(5)

In [62]:
a.mean()

np.float64(3.0)

In [63]:
np.mean(a)

np.float64(3.0)

In [64]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
a.max()

np.int64(8)

In [67]:
np.min(a)

np.int64(1)

In [68]:
a.mean()

np.float64(4.5)

In [69]:
np.sum(a)

np.int64(36)

In [70]:
# column wise checking
np.max(a,axis=0)

array([5, 6, 7, 8])

In [71]:
# row wise checking
a.min(axis=1)

array([1, 5])

In [72]:
a.sum(axis=0)

array([ 6,  8, 10, 12])

In [73]:
a.sum(axis=1)

array([10, 26])